### ISSUE TITLE
Job Details

### ISSUE THREAD

**Issue by keathley** [chadev/chatech-jobs#2]
As a User
I should be able to see a jobs details
So that I can see if that jobs specifics are interesting to me.

Job Details:

- [x] Title
- [x] Description
- [x] How to apply
- [x] Company
- [ ] Company Logo
- [ ] Company website? (Is this relevant at all?)
- [ ] Location? (Are there going to be people posting jobs from outside Chattanooga proper?

**Comment by colinrymer** [comment]
Requirements would be a handy category.

**Comment by colinrymer** [comment]
Or for Andrew - a handy column.

**Comment by keathley** [comment]
@colinrymer What do you mean by requirements?  Like, "must have a cs degree" kinda stuff?

**Comment by colinrymer** [comment]
Yeah, college degree, security clearance, etc.

**Comment by keathley** [comment]
The description is just text that we format as markdown.  So anything like that could be added there.

**Comment by seabre** [comment]
@keathley requirements like that would be handy metadata for searching/filtering. Maybe I want to filter  only python jobs? Maybe I want to filter jobs that are only in the government sector? etc.

I don't think this is required for an MVP, but it would certainly be a nice to have feature.

**Comment by keathley** [comment]
I can definitely see how this would be useful, especially for very broad categories like "Developer" and "Designer".  For the very specific stuff about "Python" or "Javascript" couldn't we just do full text searching over the description?

**Comment by keathley** [comment]
@colinrymer @seabre I've created a specific issue for filtering and searching for jobs in #18.  Lets move the discussion over there.  Enough of this stuff is done to go ahead and close this issue.
