### ISSUE TITLE
Footer position in Safari

### ISSUE THREAD

**Issue by bobbyburden** [chadev/chatech-jobs#28]
In Safari (testing in 8.1), the footer is placed at the bottom of the window. When you scroll, it remains in that original position so that it overlaps content.

Here is a screenshot showing the position on the initial page load:
![screen shot 2015-06-20 at 12 28 17 pm](https://cloud.githubusercontent.com/assets/1583460/8268359/19695786-1751-11e5-9d93-a5b829c95c43.png)

This screenshot shows the position of the footer after scrolling down a bit:
![screen shot 2015-06-20 at 12 28 20 pm](https://cloud.githubusercontent.com/assets/1583460/8268362/4018bf2a-1751-11e5-8a62-034df4442204.png)

**Comment by keathley** [comment]
This is either a problem with the flexbox implementation or with some sort of vendor prefixing issue.

**Comment by bobbyburden** [comment]
According to [CanIUse](http://caniuse.com/#search=flex), Safari requires the `webkit` prefix. But it looks like the prefix is there in the rendered CSS.

I'll dig into this some more -- it might just be a dumb Safari problem.
