### ISSUE TITLE
Share Jobs

### ISSUE THREAD

**Issue by keathley** [chadev/chatech-jobs#3]
As a User
I should be able to share jobs
So that I can help find awesome positions for my friends.

**Comment by andrunix** [comment]
Any thoughts on how that should be implemented? Click a "Share" link that opens a mail_to? Enter an email address and click Share? Other?

**Comment by keathley** [comment]
Email is a great place to start for now

**Comment by bobbyburden** [comment]
A service like AddThis's [Share Button](https://www.addthis.com/get/sharing) would make this really easy. Would we be opposed to going that route?

**Comment by keathley** [comment]
We have a share button to send emails.  I'm going to close this until someone wants to add a new method for sharing.
